go_binary(
    name = "twf",
    srcs = ["main.go"],
    deps = [
        "//internal/config",
        "//internal/filetree",
        "//internal/state",
        "//internal/terminal",
        "//internal/views",
        "//third_party:zap",
    ],
)
